apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  namespace: roboshop
  labels:
    project: roboshoop
    tier: backend
    component: shipping
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      project: roboshop
      tier: backend
      component: shipping
  template:
    metadata:
      labels:
        project: roboshop
        tier: backend
        component: shipping
    spec:
      containers:
      - name: shipping
        image: {{ .Values.deployment.imageName }}:{{ .Values.deployment.imageVersion }}
        imagePullPolicy: Always
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        readinessProbe:
          tcpSocket:
            port: 8080
          failureThreshold: 2
          periodSeconds: 10
          initialDelaySeconds: 15
        startupProbe:
          httpGet:
            path: /health
            port: 8080
          failureThreshold: 20
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          failureThreshold: 2
          periodSeconds: 10
        envFrom:
        - configMapRef:
            name: shipping