configMap:
  REDIS_HOST: "redis"
  CATALOGUE_HOST: "catalogue"
deployment:
  replicas: 1
  imageName: "annurukulasekhar/cart"
  imageVersion: "1.4.0"
horizontalPodAutoScaler:
  minReplicas: 1
  maxReplicas: 10
  averageUtilization: 20