configMap:
  REDIS_URL: "redis://redis:6379"
  MONGO_URL: "mongodb://mongodb:27017/users"
deployment:
  replicas: 1
  imageName: "annurukulasekhar/user"
  imageVersion: "1.4.0"
horizontalPodAutoScaler:
  minReplicas: 1
  maxReplicas: 10
  averageUtilization: 20