apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: roboshop
  labels:
    project: roboshop
    tier: backend
    component: payment
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      project: roboshop
      tier: backend
      component: payment
  template:
    metadata:
      labels:
        project: roboshop
        tier: backend
        component: payment
    spec:
      containers:
      - name: payment
        image: {{ .Values.deployment.imageName }}:{{ .Values.deployment.imageVersion }}
        resources:
          requests:
            memory: "120Mi"
            cpu: "100m"
          limits:
            memory: "120Mi"
            cpu: "100m"
        readinessProbe:
          tcpSocket:
            port: 8080
          failureThreshold: 2
          periodSeconds: 10
          initialDelaySeconds: 15
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          failureThreshold: 2
          periodSeconds: 10
        envFrom:
        - configMapRef:
            name: payment
        - secretRef:
            name: payment