apiVersion: v1
kind: Secret
metadata:
  name: payment
  namespace: roboshop
  labels:
    project: roboshop
    tier: db
    component: payment
data:
  AMQP_PASS: "{{ .Values.deployment.AMQP_PASS }}"
